<?php

    set_time_limit(0);
    include_once "vendor/autoload.php";

    use MVC\Core\Middleware\VerifyCsrfToken;
    use Controlador\controladorHotel;

    $controladorHotel = new controladorHotel();

    // Src: https://es.stackoverflow.com/questions/67370/obtener-ip-de-cliente-desde-php
    function getUserIpAddress() {
        foreach ( [ 'HTTP_CLIENT_IP', 'HTTP_X_FORWARDED_FOR', 'HTTP_X_FORWARDED', 'HTTP_X_CLUSTER_CLIENT_IP', 'HTTP_FORWARDED_FOR', 'HTTP_FORWARDED', 'REMOTE_ADDR' ] as $key ) {
    
            // Comprobamos si existe la clave solicitada en el array de la variable $_SERVER 
            if ( array_key_exists( $key, $_SERVER ) ) {
    
                // Eliminamos los espacios blancos del inicio y final para cada clave que existe en la variable $_SERVER 
                foreach ( array_map( 'trim', explode( ',', $_SERVER[ $key ] ) ) as $ip ) {
    
                    // Filtramos* la variable y retorna el primero que pase el filtro
                    if ( filter_var( $ip, FILTER_VALIDATE_IP, FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE ) !== false ) {
                        return $ip;
                    }
                }
            }
        }
    
        return '?'; // Retornamos '?' si no hay ninguna IP o no pase el filtro
    }
    
    function buscarHoteles($infoSesion) {
        $postAvailability["stay"]           = $infoSesion["stay"];
        $postAvailability["occupancies"]    = $infoSesion["occupancies"];
        $postAvailability["geolocation"]    = $infoSesion["geolocation"];
        $postAvailability["language"]       = "CAS";

        // Se seleccionan solamente los hoteles
        // TODO: Preguntar si tambien se filtrara por tipo de pago ["AT_HOTEL", "AT_WEB", "BOTH"]
        // $postAvailability["filter"] = (object)["paymentType" => "AT_WEB"];
        $postAvailability["accommodations"] = ["HOTEL"];
        $postAvailability["dailyRate"]      = true;

        // Source market is used on requests in order to inform Hotelbeds that you are requesting prices for a specific market.
        // This is useful because some hotels have lower prices depending on the source market of the final client.
        $ip = getUserIpAddress();

        if ($ip !== '?') {
            $postAvailability["sourceMarket"]   = json_decode(file_get_contents("http://ipinfo.io/{$ip}"))->country;
        }
        
        // Certification process verifies that, in case you request it, you are using this prices only for the source market requested.
        // For instance you cannot give at Spanish market prices obtained with the source market of United Kingdom.
        $postAvailability = json_encode( $postAvailability);

        // TODO: Descomentar cuando se trabaje con respuestas reales
        
        // Your API Key and secret from developer.hotelbeds.com
        $apiKey = HOTELBEDS_API_KEY;  
        $Secret = HOTELBEDS_SECRET;

        // Signature is generated by SHA256 (Api-Key + Secret + Timestamp (in seconds))
        $signature = hash("sha256", $apiKey.$Secret.time());

        $curl = curl_init();

        curl_setopt_array($curl, array(
            CURLOPT_URL => HOTELBEDS_API_ENDPOINT . "hotel-api/1.0/hotels",
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => "",
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 5,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => "POST",
            CURLOPT_POSTFIELDS => $postAvailability,
            CURLOPT_HTTPHEADER => array(
                "accept: application/json",
                "accept-encoding: gzip",
                "api-key: ". $apiKey ."",
                "cache-control: no-cache",
                "content-type: application/json",
                "x-signature: ". $signature .""
            ),
        ));

        $response = curl_exec($curl);
        $err = curl_error($curl);

        curl_close($curl);

        if ($err) {
            echo "cURL Error #:" . $err;
        }

        // $response = file_get_contents("respuestaDisponibilidadReciente.txt");
        $response = json_decode($response, true);
        
        session_start();
        $_SESSION["placesAutocomplete_ant"] = $infoSesion['placesAutocomplete'];
        $_SESSION['Disponibilidad']         = $response;
        $infoSesion['Disponibilidad']       = $response;
        session_write_close();

        return $response;
    }

    session_start();
    
    $infoSesion["Disponibilidad"]           = $_SESSION["Disponibilidad"]           ?? null;
    $infoSesion["stay"]                     = $_SESSION["stay"]                     ?? null;
    $infoSesion["occupancies"]              = $_SESSION["occupancies"]              ?? null;
    $infoSesion["placesAutocomplete"]       = $_SESSION["placesAutocomplete"]       ?? null;
    $infoSesion["placesAutocomplete_ant"]   = $_SESSION["placesAutocomplete_ant"]   ?? null;
    $infoSesion["geolocation"]              = $_SESSION["geolocation"]              ?? null;

    $csrfClass = new VerifyCsrfToken();

    ob_start();
    
    $csrfClass->metaTokenCsrf();
    $csrfMeta = ob_get_clean();

    session_write_close();

    $totalHabitaciones  = 0;
    $totalPersonas      = 0;
    $totalAdultos       = 0;
    $totalMenores       = 0;

    $checkIn    = new DateTime($infoSesion["stay"]["checkIn"]);
    $checkOut   = new DateTime($infoSesion["stay"]["checkOut"]);

    $nochesEstancia = $checkIn->diff($checkOut);

    //Calcula el total de personas (Por medio del filtro)
    if (isset($infoSesion["occupancies"])) {
        for ($i=0, $l=count($infoSesion["occupancies"]); $i < $l; $i++) { 
            if (isset($infoSesion["occupancies"][$i]["rooms"])) {
                $totalHabitaciones  += $infoSesion["occupancies"][$i]["rooms"];
            }

            if (isset($infoSesion["occupancies"][$i]["adults"])) {
                $totalAdultos       += $infoSesion["occupancies"][$i]["adults"];
            }
        
            if (isset($infoSesion["occupancies"][$i]["children"])) {
                $totalMenores       += $infoSesion["occupancies"][$i]["children"];
            }
        }
        
        $totalPersonas = $totalAdultos + $totalMenores;
    }

    $totalPersonas = ($totalPersonas > 0) ? $totalPersonas : 1;

    $response = null;

    // Si ya existe información de hoteles y el destino no ha cambiado entonces preguntamos por las fechas cambiaron para determinar la acción a tomar
    if( (isset($infoSesion['Disponibilidad'])) && ($infoSesion['placesAutocomplete'] === $infoSesion['placesAutocomplete_ant']) ){
        if (isset($infoSesion['Disponibilidad']['error'])) {
            $response = buscarHoteles($infoSesion);
        }

        // Si las fechas de checkIn y/o checkOut cambiaron entonces buscamos una nueva respuesta de disponibilidad
        if (isset($infoSesion['Disponibilidad']["hotels"]["checkIn"])) {
            if (($infoSesion["stay"]["checkIn"]     !== $infoSesion['Disponibilidad']["hotels"]["checkIn"]) ||
                ($infoSesion["stay"]["checkOut"]    !== $infoSesion['Disponibilidad']["hotels"]["checkOut"])) {
                $response = buscarHoteles($infoSesion);
            } else {
                $response = $infoSesion['Disponibilidad'];
            }
        }
    } else {   
        $response = buscarHoteles($infoSesion);
    }
    // header("Content-Type: application/json; charset=UTF8");

    if (false) {
        for ($h=0, $limite=count($response['hotels']['hotels']); $h < $limite; $h++) { 
            $hotelSeleccionado = $response["hotels"]["hotels"][$h];
            $habitaciones = 0;
    
            // Aqui se adapta la respuesta de las habitaciones en base a si hay una búsqueda efectuada o simplemente se muestren todos los datos de la BDD
            if (isset($hotelSeleccionado["rooms"])) {
                for ($i=0, $l=count($hotelSeleccionado["rooms"]); $i<$l; $i++) { 
                    $codigosHabitacion[] = $hotelSeleccionado["rooms"][$i]["code"];
                }
    
                $habitaciones = $hotelSeleccionado["rooms"];
            }
    
            $noHabitaciones     = count($habitaciones);
    
            $arrRecheck = [
                "rateKeyRecheck"    => [],
                "rateKey"           => [],
                "i"                 => [],
                "j"                 => []
            ];
        
            $contArrRecheck = 0;
        
            for ($i=0, $l=$noHabitaciones; $i<$l; $i++) {
                if (isset($hotelSeleccionado["rooms"][$i]["rates"])) {
                    for ($j=0, $m=count($hotelSeleccionado["rooms"][$i]["rates"]); $j < $m; $j++) {
                        if (isset($hotelSeleccionado["rooms"][$i]["rates"][$j]["rateType"])) {
                            if ($hotelSeleccionado["rooms"][$i]["rates"][$j]["rateType"] == "RECHECK") {
                                $rateKeyRecheck = $hotelSeleccionado["rooms"][$i]["rates"][$j]["rateKey"];
        
                                $arrRecheck["rateKeyRecheck"][$contArrRecheck][] = (object) ["rateKey" => $rateKeyRecheck];
                                $arrRecheck["rateKeyStr"][$contArrRecheck][]     = $rateKeyRecheck;
                                $arrRecheck["i"][$contArrRecheck][]              = $i;
                                $arrRecheck["j"][$contArrRecheck][]              = $j;
                                
                                if ((count($arrRecheck["rateKeyRecheck"][$contArrRecheck]) % 10) === 0) {
                                    $contArrRecheck = $contArrRecheck + 1;
                                }
                            }
                        }
                    }
                }
            }
    
            for ($i=0, $l=count($arrRecheck["rateKeyRecheck"]); $i<$l; $i++) {
                $postRecheck = json_encode(["rooms" => $arrRecheck["rateKeyRecheck"][$i], "language" => "CAS"]);

                // echo $postRecheck . "<br><br><br>";
                // continue;

    
                // Your API Key and secret from developer.hotelbeds.com
                $apiKey = HOTELBEDS_API_KEY;  
                $Secret = HOTELBEDS_SECRET;
                
                // Signature is generated by SHA256 (Api-Key + Secret + Timestamp (in seconds))
                $signature = hash("sha256", $apiKey.$Secret.time());
                
                $curl = curl_init();
                curl_setopt_array($curl, array(
                    CURLOPT_URL => HOTELBEDS_API_ENDPOINT . "hotel-api/1.0/checkrates",
                    CURLOPT_RETURNTRANSFER => true,
                    CURLOPT_ENCODING => "",
                    CURLOPT_MAXREDIRS => 10,
                    CURLOPT_TIMEOUT => 15,
                    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
                    CURLOPT_CUSTOMREQUEST => "POST",
                    CURLOPT_POSTFIELDS => $postRecheck,
                    CURLOPT_HTTPHEADER => array(
                        "accept: application/json",
                        "accept-encoding: gzip",
                        "api-key: ". $apiKey ."",
                        "cache-control: no-cache",
                        "content-type: application/json",
                        "x-signature: ". $signature .""
                    ),
                ));
                
                $responseRecheck = curl_exec($curl);

                // echo $responseRecheck . "<br><br><br>";
                // continue;
                
                $responseRecheck = json_decode($responseRecheck, true);
    
                
                $err = curl_error($curl);
                curl_close($curl);
                
                if ($err) {
                    echo "cURL Error #:" . $err;
                }
                
                if (isset($responseRecheck["hotel"]["rooms"])) {
                    for ($cont1 = 0, $limit1 = count($responseRecheck["hotel"]["rooms"]); $cont1 < $limit1; $cont1++) {
                        if (isset($responseRecheck["hotel"]["rooms"][$cont1]["rates"])) {
                            for ($j=0, $m=count($responseRecheck["hotel"]["rooms"][$cont1]["rates"]); $j<$m; $j++) {
                                $rateKeyActual = $responseRecheck["hotel"]["rooms"][$cont1]["rates"][$j]["rateKey"];
                    
                                $indexRateKey = array_search($rateKeyActual, $arrRecheck["rateKeyStr"][$i]);
                    
                                if ($indexRateKey !== false) {
                                    // echo $arrRecheck["rateKeyStr"][$i][$indexRateKey];
                                    // continue;

                                    $i_original = $arrRecheck["i"][$i][$indexRateKey];
                                    $j_original = $arrRecheck["j"][$i][$indexRateKey];
                        
                                    $llavesRecheckRR = array_keys($responseRecheck["hotel"]["rooms"][$cont1]["rates"][$j]);
                        
                                    // Se recorren todas las llaves de la respuesta para actualizar en la respuesta de disponibilidad
                                    for ($k=0, $n=count($llavesRecheckRR); $k < $n; $k++) { 
                                        $hotelSeleccionado["rooms"][$i_original]["rates"][$j_original][$llavesRecheckRR[$k]] = $responseRecheck["hotel"]["rooms"][$cont1]["rates"][$j][$llavesRecheckRR[$k]];
                                    }
            
                                    // Se actualiza la respuesta de recheck en la respuesta de disponibilidad original que se tiene guardada en la sesion
                                    $response["hotels"]["hotels"][$h] = $hotelSeleccionado;
                                }
                            }
                        }
                    }
                }
            }
        }

        session_start();
        $_SESSION["Disponibilidad"] = $response;
        session_write_close();
    }

    $HotelPorPagina = 25;
    $pagina = 1;

    if(isset($_GET['pagina'])){
        $pagina = $_GET['pagina'];
    }

    $str = rand();
    $Codigo = md5($str);
    $codigoTabla = $Codigo;
?>

<!DOCTYPE html>
<html lang="es">
<head>
    <?php
        if ( $_SERVER["DOCUMENT_ROOT"] == 'C:/xampp/htdocs' ) {
            $servidor = "http://localhost/lexgotravel/";
        } else {
            $servidor = "https://lexgotravel.com/";
        }
    ?>
    <base href="<?php echo $servidor ?>public/" >
    
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php echo $csrfMeta; ?>

    <title>Hoteles | <?php echo $infoSesion["placesAutocomplete"]; ?></title>

    <!-- Select2 -->
    <link rel="stylesheet" href="css/select2/select2.min.css">

    <?php include ("links.php") ?>
</head>
<body>
    <!--HEADER-->
    <?php include ("header.php") ?>
    <!--FIN HEADER-->

    <!--BODY-->
    <?php 
        use Controlador\controladorAPI_BD;
        use Classes\funciones;
        use Classes\temporaryClass;
        use Classes\typesHotel;
        
        $temp   = new temporaryClass();
        
        $planesTip = $temp->TipPlanes();
        $cplanesTip = count($planesTip["code"]);

        if (isset($response["hotels"]["hotels"])) {
            
            $cons   = new controladorAPI_BD();
            $fn     = new funciones();
            $type   = new TypesHotel();
    
            $RespuestaTemporaryTables = $temp->CreateTemporaryTable($response, $codigoTabla);
    
            // Destino
            $txtDestino = $response["hotels"]["hotels"][0]["destinationName"];
            
            ///////////////////////////////////
            // Convertidor de divisas
            require_once('utils/currencyConverter.php');
            
            function masRepetido($n)
            {
                $valores = array_count_values($n);
                arsort($valores);
                return count($valores) > 0 ? array_key_first($valores)  : "";
            }
    
            foreach ($response["hotels"]["hotels"] as $hotelClave => $hotelValor) {
                $currency[] = $hotelValor["currency"];
                $minRates[] = $hotelValor["minRate"];
            }
    
            // Divisa a la cual se quiere convertir
            $ToCurrency     = 'MXN';
    
            // Arreglo de divisas que manejan los hoteles
            $currency = array_unique($currency, SORT_STRING );
    
            foreach ($currency as $currencyClave => $currencyValor) {
				if ($currencyValor === "MXN") {
					$valor[$currencyValor] =  1;
				} else {
					$converter = new currencyConverter(1, $ToCurrency, $currencyValor);
					$valor[$currencyValor] =  $converter->getUpdate();
				}
            }
			
            $divisaMasRepetida = masRepetido($currency);
            ///////////////////////////////////
            // Fin convertidor de divisas

            $PrefHabitaciones = $temp->PrefHabitaciones($codigoTabla);
            $cPrefHabitaciones = count($PrefHabitaciones["code"]);
    
            $GetContadorHoteles = $temp->ConteoDeHoteles($codigoTabla);
    
            $limit = $HotelPorPagina;
            $offset = ($pagina - 1) * $limit;
    
            $GetHoteles = $temp->GetHotelesDisponibles($codigoTabla,$limit,$offset);
            $cGetHoteles = count($GetHoteles["id"]);
    
            $paginas = ceil((int)$GetContadorHoteles['contador'][0] / (int)$HotelPorPagina);
    
            // Se obtiene la descripcion y la imagen del hotel desde la BDD local
            $txt = $GetHoteles['code'][0];
                    
            for($i=1; $i<$cGetHoteles; $i++){
                $txt .= "," . $GetHoteles['code'][$i];
            }
            
            $datos = $controladorHotel->leerHoteles($txt);
            $datos = json_decode($datos, true);
    
            $txt = "";
            for($i=0; $i < $cGetHoteles; $i++){
                $indiceConsulta = array_search($GetHoteles['code'][$i], $datos["code"]);
    
                if (is_int($indiceConsulta)) {
                    if ($i > 0) {
                        $txt .= "," . $datos['id'][$indiceConsulta];
                    } else {
                        $txt .= $datos['id'][$indiceConsulta];
                    }
                }
            }
    
            $facilidades = $controladorHotel->hotelFacilidades($txt, "facilityCode,facilityGroupCode,id_hotel_description");
            $facilidades = json_decode($facilidades, true);
        }
    ?>

    <!--PRINCIPAL SIDEBAR-->
    <div class="row m-0 w-100 p-0">
        <!--SIDEBAR-->
        <div id="barra-lateral" class="col-md-3 p-0" style="background: #228ce3 !important;">
            <div id="contenedor-busqueda_filtro">
                <div class="m-0 p-0" style="background-size:cover; background-image:url('medios/img/mdb/cuadromotordebusqueda.png');">
                    <h2 class="text-white m-3 ms-5" style="border-bottom: 4px solid white; position: relative; margin-right: 0px !important;">Buscar</h2>
                    <div class="mx-5">
                        
                        <form method="POST" action="../motordebusqueda">
                            <p class="text-white">Destino</p>

                            <div class="w-100 m-0 p-0 camp-filtro d-flex justify-content-center align-items-center">
                                <div class="icon-filtro-mdb-container">
                                    <img class="icon-filtro-mdb" src="medios/img/mdb/isotipo1motordebusqueda.png" alt="Icono Filtro">
                                </div>

                                <div class="w-100">
                                    <style>
                                        #location {
                                            font-size: 0.9rem;
                                        }
                        
                                        #location::placeholder {
                                            color: white;
                                        }
                                    </style>

                                    <input id="location" placeholder="Seleccionar destino" style="background-color:transparent; border: none; color: white;"/>
                                </div>
                            </div>
                            
                            <div class="row">
                                <div class="col-6">
                                    <p class="text-white">Check in</p>
                                </div>
                                <div class="col-6">
                                    <p class="text-white">Check out</p>
                                </div>
                            </div>
                            
                            <div class="d-flex align-items-center input-group mb-3 p-2" style="padding: 2px; border: 2px solid white;">
                                <div class="col-6 m-0 p-0 d-flex align-items-center">
                                    
                                    <input id="checkIn" type="date" value="" class="form-control p-1" style="font-size: 11px; background: #228ce300; border: none; border-right: 2px solid white !important; color:white; border-radius: 0px;" aria-label="Dollar amount (with dot and two decimal places)">
                                    
                                </div>
                                <div class="col-6 m-0 p-0 d-flex align-items-center">
                                    
                                    <input id="checkOut" type="date" value="" class="form-control p-1" style="font-size: 11px; background: #228ce300; color:white; border: none;" aria-label="Dollar amount (with dot and two decimal places)">
                                    
                                </div>
                            </div>
                            
                            <div class="d-flex align-items-center mb-2 text-center">
                                <input type="checkbox" class="switch mx-2"><p class="text-white">Sin fecha definida</p>
                            </div>
                            
                            
                            <div class="d-flex align-items-center mb-2 text-center">
                                
                                <input type="checkbox" class="switch mx-2"><p class="text-white">Viaje de trabajo</p>
                            </div>
                            <div class="mx-auto">
                                <div class="mx-auto d-flex align-items-center justify-content-center text-center mb-2" style="width: 100%; padding: 2px; border: 2px solid white;">
                                    <div>
                                        <ul class="nav-items m-0" style="padding:1px;">
                                            <li class="nav-item dropdown">
                                                <a href="" class="nav-link"><p style="color:White !important">
                                                    <div class="mx-auto d-flex align-items-center justify-content-center text-center">
                                                        <img class="mx-2" src="medios/img/mdb/iconohabitacionmotor.png" alt="" style="height: 19px;"><p id="cantidadHabitaciones" class="text-white">1</p>
                                                        <img class="mx-2" src="medios/img/mdb/iconoadultomotor.png" alt="" style="height: 19px;"><p id="cantidadAdultos" class="text-white">1</p>
                                                        <img class="mx-2" src="medios/img/mdb/iconomenormotor.png" alt="" style="height: 19px;"><p id="cantidadMenores" class="text-white">0</p>
                                                    </div>
                                                </p></a>
                                                <nav class="submenu">
                                                    <div id="submenu-qty" class="submenu-qty">
                                                        <ul class="submenu-items clonar">
                                                        <li class="submenu-item">
                                                                <a href="#" class="submenu-link">
                                                                    <div class="">
                                                                        <div class="row col-12 ">
                                                                            <div class="col-sm-5 ">
                                                                                <h3 for="" class="color" style="color:#228ce3 !important;">Adultos</h3>
                                                                                <label for="" class="white" style="font-size: 12px;">Desde los 18 años</label>
                                                                            </div>  
                                                                            <div class="col-sm-3 inputnumber">
                                                                                <div class="number-input">
                                                                                    <button class="minus minusAdults"></button>
                                                                                    <input class="quantity" min="1" max="8" name="quantity" value="1" type="number">
                                                                                    <button class="plus plusAdults"></button>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </a>
                                                            </li> 
                                                            <li class="submenu-item">
                                                                <a href="#" class="submenu-link">
                                                                    <div class="">
                                                                        <div class="row col-12">
                                                                            <div class="col-sm-5">
                                                                                <h3 for="" class="color" style="color:#228ce3 !important;">Menores</h3>
                                                                                <label for="" class="white" style="font-size: 12px;">Menores de 17 años</label>
                                                                            </div>
                                                                            <div class="col-sm-3 inputnumber">
                                                                                <div class="number-input">
                                                                                    <button class="minus minusMinors"></button>
                                                                                    <input class="quantity" min="0" name="quantity" value="0" type="number">
                                                                                    <button class="plus plusMinors"></button>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </a>
                                                            </li>
                                                        </ul>
                                                    </div>
                            
                                                    <div class="d-flex btn-add-habit">
                                                        <button class="btn btn-primary" id="agregar">Agregar habitación +</button>
                                                    </div>
                                                </nav>
                                            </li> 
                                        </ul> 
                                    </div>
                                </div>
                            </div>
                            
                            <div class="d-flex justify-content-center align-items-center mb-3 text-center">
                                <img class="" src="medios/img/mdb/go.png" style="height: 24px;" alt=" ">
                                <a id="btn-buscar" href="../motordebusqueda" class="nav-link link-light bg-black px-1 py-1 my-1 mx-1" style="width: 148px;">Buscar</a>
                            </div>
                        </form>

                    </div>
                </div>
                
                <div class="bg-white m-1 p-3">
                    <!--PRECIO-->
                    <form id="filtrosForm">
                        <div>

                            <!-- <p style="margin-bottom: 15px;">Presupuesto total por noche:</p> -->
                            <p style="margin-bottom: 15px;">Presupuesto total:</p>

                            <div id="slider-range" class="price-filter-range w-100" name="rangeInput"></div>

                            <div>
                                <span class="text-start float-start text-rang-price">Desde -&nbsp;</span>
                                <input type="text" id="min_price" class="price-range-field fw-bold" name="precioMin" >

                                <span class="text-end float-end text-rang-price">&nbsp;- Hasta</span>
                                <input type="text" id="max_price" class="price-range-field float-end fw-bold text-end" name="precioMax" >
                            </div>

                            <!-- <button class="price-range-search" id="price-range-submit">Search</button> -->
                        </div>
                        <!--FILTROS-->
                        
                        <div class="m-3" style="border-bottom: 2px solid #f7f7f7;">
                            <select id="categoria" class="form-select m-0" aria-label="Default select example" name="categoria">
                                <option value="0"selected>Categoría de hotel</option>
                                <option value="1">1 Estrellas</option>
                                <option value="2">2 Estrellas</option>
                                <option value="3">3 Estrellas</option>
                                <option value="4">4 Estrellas</option>
                                <option value="5">5 Estrellas</option>
                                <option value="6">Otros</option>
                            </select>
                        </div>
                        <div class="m-3" style="border-bottom: 2px solid #f7f7f7;">
                            <select class="form-select m-0 selectTipCamas" aria-label="Default select example" style="border-bottom: 2px solid #f7f7f7;" name="tipCama">
                                <option selected>Preferencia de camas</option>
                                <?php if (isset($response["hotels"]["hotels"])) {
                                        for($t=0;$t<$cPrefHabitaciones;$t++) { ?>
                                            <option value="<?php echo $PrefHabitaciones['code'][$t]; ?>"><?php echo $PrefHabitaciones['name'][$t]; ?></option>
                                <?php   }
                                    } ?>
                            </select>
                        </div>
                        <div class="m-3" style="border-bottom: 2px solid #f7f7f7;">
                            <select class="form-select m-0 selectTipPlanes" aria-label="Default select example" name="tipPlanes">
                                <option selected>Tipos de planes</option>
                                <?php if (isset($response["hotels"]["hotels"])) {
                                        for($t=0;$t<$cplanesTip;$t++){ ?>
                                    <option value="<?php echo $planesTip['code'][$t]; ?>"><?php echo $planesTip['description'][$t]; ?></option>
                                <?php  }
                                    } ?>
                                
                            </select>
                        </div>
                        <div>
                            <input class="btn-red w-100" type="button" onclick="filtroEstrellas('<?php echo $dispositivo = 'pc'; ?>')" value="Calcula"/>
                        </div>
                    </form>

                </div>
            </div>
            
            <div class="">
                <div id="secc-nuest-viaj" class="w-100 col-md-3 bg-white p-5 m-0">
                    <div class="text-center py-5 my-5">
                        <img class="mb-2" src="medios/img/Logolexgotoursinferior.png" alt="">
                        <h6 style="color:#e3223e;">Conoce nuestro México <br>con nuestros tours guiados</h6>
                    </div>

                </div>
                <div id="secc-nuest-viaj" class="w-100 col-md-3 p-5 m-0" style="background:#ff7d00;">
                    <div class="text-center py-5 my-5">
                        <img class="mb-2" src="medios/img/Logolextransferinferior.png" alt="">
                        <h6 class="text-white text-uppercase">Nosotros te llevamos<br>en el mejor transporte</h6>
                    </div>
                    
                </div>
            </div>
            
            
           
        </div>
        <!--SEDEBAR MOVIL-->
        <div id="filtro-movil-ocult">
            
            <button class="btn btn-primary w-100 m-1" style="background:#228ce3;" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample">
            Filtro
            </button>

            <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
                <div class="offcanvas-header" style="background: #228ce3; border-bottom: 4px solid white;">
                    <h2 class="offcanvas-title text-white" id="offcanvasExampleLabel" >Buscar</h2>
                    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" style="color:white !important;" aria-label="Close"></button>
                </div>
                <!--AQUI INICIA EL MENÚ MÓVIL-->
                <div class="offcanvas-body p-0" style="background: #228ce3;">
                    <div class="bg-white m-1 p-3">
                    <!--PRECIO-->
                    <form id="filtrosFormMovil">
                        <div>
                            <!-- <p style="margin-bottom: 15px;">Presupuesto total por noche:</p> -->
                            <p style="margin-bottom: 15px;">Presupuesto total:</p>

                            <div id="slider-range-movil" class="price-filter-range w-100" name="rangeInput"></div>

                            <div>
                                <span class="text-start float-start text-rang-price">Desde -&nbsp;</span>
                                <input type="text" id="min_price-movil" class="price-range-field fw-bold" name="precioMin" >
                                
                                <span class="text-end float-end text-rang-price">&nbsp;- Hasta</span>
                                <input type="text" id="max_price-movil" class="price-range-field float-end fw-bold text-end" name="precioMax" >
                            </div>

                        <!--button class="price-range-search" id="">Search</button-->
                        </div>
                        <!--FILTROS-->
                        
                        <div class="m-3" style="border-bottom: 2px solid #f7f7f7;">
                            <select class="form-select m-0 selectTipCategorias-movil" aria-label="Default select example" name="categoria" multiple>
                                <!-- <option value="0" selected>Categoría de hotel</option> -->
                                <option value="1">1 Estrellas</option>
                                <option value="2">2 Estrellas</option>
                                <option value="3">3 Estrellas</option>
                                <option value="4">4 Estrellas</option>
                                <option value="5">5 Estrellas</option>
                                <option value="6">Otros</option>
                            </select>
                        </div>
                        <div class="m-3" style="border-bottom: 2px solid #f7f7f7;">
                            <select class="form-select m-0 selectTipCamas-movil" style="border-bottom: 2px solid #f7f7f7;" name="tipCama" multiple>
                                <!-- <option selected>Preferencia de camas</option> -->
                                <?php if (isset($response["hotels"]["hotels"])) {
                                        for($t=0; $t<$cPrefHabitaciones; $t++){ ?>
                                    <option value="<?php echo $PrefHabitaciones['code'][$t]; ?>"><?php echo $PrefHabitaciones['name'][$t]; ?></option>
                                <?php  }
                                } ?>
                            </select>
                        </div>
                        
                        <div class="m-3" style="border-bottom: 2px solid #f7f7f7;">
                            <select class="form-select m-0 selectTipPlanes-movil" name="tipPlanes" multiple>
                                <!-- <option selected>Tipos de planes</option> -->
                                <?php if (isset($response["hotels"]["hotels"])) {
                                        for($t=0; $t<$cplanesTip; $t++){ ?>
                                    <option value="<?php echo $planesTip['code'][$t]; ?>"><?php echo $planesTip['description'][$t]; ?></option>
                                <?php  }
                                } ?>
                                
                            </select>
                        </div>

                        <div>
                            <input class="btn-red w-100" type="button" onclick="filtroEstrellas('<?php echo $dispositivo = 'movil'; ?>')" value="Calcula"/>
                        </div>
                    </form>

                </div>
            <div class="">
                <div id="secc-nuest-viaj" class="w-100 col-md-3 bg-white p-5 m-0">
                    <div class="text-center py-5 my-5">
                        <img class="mb-2" src="medios/img/Logolexgotoursinferior.png" alt="">
                        <h6 style="color:#e3223e;">Conoce nuestro México <br>con nuestros tours guiados</h6>
                    </div>

                </div>
                <div id="secc-nuest-viaj" class="w-100 col-md-3 p-5 m-0" style="background:#ff7d00;">
                    <div class="text-center py-5 my-5">
                        <img class="mb-2" src="medios/img/Logolextransferinferior.png" alt="">
                        <h6 class="text-white text-uppercase">Nosotros te llevamos<br>en el mejor transporte</h6>
                    </div>  
                    
                </div>
            </div>


                </div>
            </div>
        </div>
       

        <!--PRINCIPAL-->
        
        <div id="hotelesList" class="col-md-9 p-0"  style="background: #f7f7f7 !important;">
            <?php if (isset($response["hotels"]["hotels"])) { ?>
            <div>
                <nav>
                    <div class="row w-100">
                        <div class="col-xs-12 col-sm-6">
                            <h4 class="pag-num-hot fw-bold">Mostrando <?php echo ($GetContadorHoteles['contador'][0] < $HotelPorPagina) ? $GetContadorHoteles['contador'][0] : $HotelPorPagina; ?> de <?php echo $GetContadorHoteles['contador'][0]; ?> Hoteles disponibles</h4>
                        </div>
                        <div class="col-xs-12 col-sm-6">
                            <p class="pag-num-pag"><b>Página</b> <?php echo $pagina ?> de <?php echo $paginas ?> </p>
                        </div>
                    </div>
                    <ul class="pagination">
                        <!-- Si la página actual es mayor a uno, mostramos el botón para ir una página atrás -->
                        <?php if ($pagina > 1) { ?>
                            <li class="paginacion">
                                <a href="./../motordebusqueda?pagina=<?php echo $pagina - 1 ?>">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                        <?php } ?>

                        <!-- Mostramos enlaces para ir a todas las páginas. Es un simple ciclo for-->
                        <?php for ($x = 1; $x <= $paginas; $x++) { ?>
                            <li class="<?php if ($x == $pagina) echo "active" ?> paginacion">
                                <a class="pag-act fw-bold" href="./../motordebusqueda?pagina=<?php echo $x ?>">
                                    <?php echo $x ?></a>
                            </li>
                        <?php } ?>
                        <!-- Si la página actual es menor al total de páginas, mostramos un botón para ir una página adelante -->
                        <?php if ($pagina < $paginas) { ?>
                            <li class="paginacion">
                                <a href="./../motordebusqueda?pagina=<?php echo $pagina + 1 ?>">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        <?php } ?>
                    </ul>
                </nav>
            </div>

            <?php
                function filtrado($a, $code) {
                    $arrFiltrado = [];
                    
                    for ($i = 0, $l=count($a["id_hotel_description"]); $i < $l; $i++) {
                        if ($a["id_hotel_description"][$i] == $code) {
                            $arrFiltrado["facilityCode"][]              = $a["facilityCode"][$i];
                            $arrFiltrado["facilityGroupCode"][]         = $a["facilityGroupCode"][$i];
                            $arrFiltrado["id_hotel_description"][]      = $a["id_hotel_description"][$i];
                        }
                    }
                    
                    return $arrFiltrado;
                };

                for($i=0; $i < $cGetHoteles; $i++){
                    $divisa = $response["hotels"]["hotels"][$i]["currency"];

                    $indiceConsulta = array_search($GetHoteles['code'][$i], $datos["code"]);
                    $facilidadesActual = filtrado($facilidades, $datos['id'][$indiceConsulta]);
                    
                    $txtFacilidades = "";

                    if (isset($facilidadesActual["facilityCode"])) {
                        if (array_search('550', $facilidadesActual["facilityCode"]) && array_search('70', $facilidadesActual["facilityGroupCode"])) {
                            $txtFacilidades .= '<span class="d-inline-block mx-1" tabindex="0" data-bs-toggle="tooltip" title="Ofrece WiFi"><img class="star-hotel mt-1" style="height: 16px;" src="medios/img/mdb/iconowifilista.png" alt=""></a></span>';
                        }

                        if ( (array_search('470', $facilidadesActual["facilityCode"]) && array_search('70', $facilidadesActual["facilityGroupCode"])) || (array_search('308', $facilidadesActual["facilityCode"]) && array_search('60', $facilidadesActual["facilityGroupCode"]))) {
                            $txtFacilidades .= '<span class="d-inline-block mx-1" tabindex="0" data-bs-toggle="tooltip" title="Cuenta con Gimnasio"><img class="star-hotel mt-1" style="height: 16px;" src="medios/img/mdb/iconogymlista.png" alt=""></a></span>';
                        }

                        if (array_search('360', $facilidadesActual["facilityCode"]) && array_search('73', $facilidadesActual["facilityGroupCode"])) {
                            $txtFacilidades .= '<span class="d-inline-block mx-1" tabindex="0" data-bs-toggle="tooltip" title="Alberca"><img class="star-hotel mt-1" style="height: 16px;" src="medios/img/mdb/iconoalbercalista.png" alt=""></a></span>';
                        }

                        if ( (array_search('201', $facilidadesActual["facilityCode"]) && array_search('288', $facilidadesActual["facilityGroupCode"])) || (array_search('202', $facilidadesActual["facilityCode"]) && array_search('288', $facilidadesActual["facilityGroupCode"])) || (array_search('55', $facilidadesActual["facilityCode"]) && array_search('60', $facilidadesActual["facilityGroupCode"])) ) {
                            $txtFacilidades .= '<span class="d-inline-block mx-1" tabindex="0" data-bs-toggle="tooltip" title="Televisión"><img class="star-hotel mt-1" style="height: 16px;" src="medios/img/mdb/iconotvlista.png" alt=""></a></span>';
                        }

                        if ( (array_search('200', $facilidadesActual["facilityCode"]) && array_search('71', $facilidadesActual["facilityGroupCode"])) || (array_search('560', $facilidadesActual["facilityCode"]) && array_search('71', $facilidadesActual["facilityGroupCode"]))) {
                            $txtFacilidades .= '<span class="d-inline-block mx-1" tabindex="0" data-bs-toggle="tooltip" title="Restaurante"><img class="star-hotel mt-1" style="height: 16px;" src="medios/img/mdb/iconocomidalista.png" alt=""></a></span>';
                        }

                        if ( (array_search('320', $facilidadesActual["facilityCode"]) && array_search('70', $facilidadesActual["facilityGroupCode"])) || (array_search('330', $facilidadesActual["facilityCode"]) && array_search('70', $facilidadesActual["facilityGroupCode"]))) {
                            $txtFacilidades .= '<span class="d-inline-block mx-1" tabindex="0" data-bs-toggle="tooltip" title="Servicio de estacionamiento"><img class="star-hotel mt-1" style="height: 16px;" src="medios/img/mdb/iconoestacionamientolista.png" alt=""></a></span>';
                        }
                    }
                
                    $descripcion = is_int($indiceConsulta) ? $datos["description"][$indiceConsulta] : "";

                    if(strlen($descripcion) > 768){
                        // Entonces corta la cadena y ponle el sufijo
                        $descripcion = substr($descripcion, 0, 768) . "...";
                    }

                    if (isset($datos["path"][$indiceConsulta])) {
                        $img = is_int($indiceConsulta) ? "https://photos.hotelbeds.com/giata/bigger/" . $datos["path"][$indiceConsulta] : "medios/img/not-found.png";
                    } else {
                        $img = "medios/img/not-found.png";
                    }
                    
                    // Estrellas del hotel
                    $estrellas = $GetHoteles["categoryCode"][$i];

                    if ($estrellas == "MINI") {
                        $estrellas = 2;
                    } else if (($estrellas == "BB") || ($estrellas == "BB3")) {
                        $estrellas = 3;
                    } else if (($estrellas == "SUP") || ($estrellas == "BOU") || ($estrellas == "BB4")) {
                        $estrellas = 4;
                    } else if (($estrellas == "HIST") || ($estrellas == "BB5")) { 
                        $estrellas = 5;
                    } else {
                        $matches = [];

                        preg_match_all("/\d/", $estrellas, $matches);
                        $estrellas = implode(".", $matches[0]);
                        $estrellas = round( $estrellas, 0, PHP_ROUND_HALF_UP);
                    }                                    

                    $estrellas = ($estrellas > 5) ? 5 : $estrellas;
                
                    $hotelEstrellas     = $estrellas;
                    $htmlEstrellas      = "";
                    $noHabitaciones     = count($response["hotels"]["hotels"][$i]["rooms"]);
                    $noHabPrecioBajo    = $response["hotels"]["hotels"][$i]["rooms"][0]["rates"][0]["allotment"];

                    $txtAlertNoHab = "";

                    if ($noHabPrecioBajo < 5) {
                        $txtAlertNoHab = "<p class='text-center mx-5 my-2 mb-0 p-1' style='border: 2px solid red;'>Solo quedan $noHabPrecioBajo habitaciones a este precio</p>";
                    }

                    $popoverTiposHabitacion = "";
                    for ($j=0; $j < $noHabitaciones; $j++) { 
                        $popoverTiposHabitacion .= ucfirst(mb_strtolower($response["hotels"]["hotels"][$i]["rooms"][$j]["name"] . "<br>"));
                    }
                    $txtDestino = $GetHoteles["destinationName"][$i];
                                        
                    // Distancia del destino al hotel
                    //Get latitude and longitude from geo data                    
                    $latitudeFrom       = $infoSesion["geolocation"]["latitude"];
                    $longitudeFrom      = $infoSesion["geolocation"]["longitude"];
                    $latitudeTo         = $GetHoteles['latitude'][$i];
                    $longitudeTo        = $GetHoteles["longitude"][$i];
                
                    //Calculate distance from latitude and longitude
                    $theta  = $longitudeFrom - $longitudeTo;
                    $dist   = sin(deg2rad($latitudeFrom)) * sin(deg2rad($latitudeTo)) +  cos(deg2rad($latitudeFrom)) * cos(deg2rad($latitudeTo)) * cos(deg2rad($theta));
                    $dist   = acos($dist);
                    $dist   = rad2deg($dist);
                    $miles  = $dist * 60 * 1.1515;
                
                    $txtDistancia = number_format($miles * 1.609344, 1) . ' km';

                    // Politicas de cancelación
                    $contentPopOver = "Este hotel no cuenta con fechas de cancelacion";

                    if (isset($response['hotels']['hotels'][$i]['rooms'][0]['rates'][0]['cancellationPolicies'][0])) {
                        $infoLimiteCancelacionGratis = '';

                        if (isset($jsonRespuesta['hotels']['hotels'][$i]['rooms'][0]['rates'][0]['cancellationPolicies'])) {
                            $infoLimiteCancelacionGratis = $response['hotels']['hotels'][$i]['rooms'][0]['rates'][0]['cancellationPolicies'][0];

                            $txtFecha = $infoLimiteCancelacionGratis['from'];
                            $txtFecha = explode("T", $txtFecha)[0];
                            $formato = 'Y-m-d';
                            $fecha = DateTime::createFromFormat($formato, $txtFecha);
                            $fecha = $fecha->format('Y-m-d');

                            $precioCancelacion = number_format($infoLimiteCancelacionGratis['amount'] * $valor[$divisa], 2);

                            $contentPopOver = "Puedes cancelar totalmente gratis hasta el $fecha, fecha a partir de la cual el precio de cancelacion es $precioCancelacion MXN. Mas informacion de los precios de cancelación en los detalles del hotel...";
                        }
                    }

                    $txtPoliticasCancelacion = "<a class='d-inline-block text-decoration-underline m-0 text-center' tabindex='0' style='font-size: 11px !important;' title='' data-bs-placement='right' data-bs-toggle='popover' data-bs-trigger='hover focus' data-bs-content='$contentPopOver' data-bs-original-title='Información cancelación'>
                                                    Políticas de cancelación
                                                    <svg xmlns='http://www.w3.org/2000/svg' width='14' height='14' fill='currentColor' class='bi bi-info-circle' style='margin: 0 0 0.2rem 0.25rem' viewBox='0 0 16 16'>
                                                        <path d='M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z'></path>
                                                        <path d='m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z'></path>
                                                    </svg>
                                                </a>";

                    $txtAdultosMenoresHabitaciones = ($totalAdultos === 1) ? "$totalAdultos Adulto" : "$totalAdultos Adultos";

                    if ($totalMenores > 0) {
                        $txtAdultosMenoresHabitaciones .= ($totalMenores === 1) ? " + $totalMenores Menor" : " + $totalMenores Menores";
                    }

                    $txtAdultosMenoresHabitaciones .= ($totalHabitaciones === 1) ? " / $totalHabitaciones Habitación" : " / $totalHabitaciones Habitaciónes";
                    
                        
                    $template = '
                    <div id="hotel-info" class="row w-100 p-5 m-0" style="padding-right: 0px !important;">
                        <div class="col-md-8 p-0 h-100"  >
                            <div class="w-100 d-flex justify-content-end"><img class="" src="medios/img/mdb/allinclusivehoteleslista.png" alt=""></div> 
                            <div class="w-100 p-4" style="background: white !important; border-radius: 20px 0px 0px 20px;">
                                <h3 class="tit2">$nombreHotel</h3>
                                <p class="mb-3">$destinationName | <a data-gall="iframe" class="venoboxframe" data-vbtype="iframe" href="$ubicacionMapa" style="font-weight: 700;">Mostrar en el mapa</a> |a $distancia de $destino</p>
                                <div class="nav align-middle">
                                    $estrellas
                                </div>
                                <div class="row w-100">
                                    <div class="col-md-6">
                                        <div class="row w-100 mb-2">
                                            <div class="col-md-6">
                                                
                                                <p class="m-0">Servicios incluidos</p>
                                                <div class="nav align-middle">
                                                    $txtFacilidades
                                                </div>
                                            </div>
                                            <div class="col-md-6 p-0">
                                                <a class="btn btn-sm btn-link" role="button" data-bs-toggle="popover" tabindex="0" title="" data-bs-placement="auto" data-bs-trigger="hover focus" data-bs-html="true" data-bs-content="$popoverTiposHabitacion" data-bs-original-title="Tipos de habitación"><p class="text-white text-center m-0 p-1" style="background: #228ce3;">$noHabitaciones Tipos de habitacion disp.</p></a>
                                            </div>

                                        </div>
                                        <p class="text-center">$txtAdultosMenoresHabitaciones</p>
                                        <p class="text-center m-0">$nochesEstancia</p>
                                        <h3 class="text-center m-0 fw-bold" style="color:#e3223e;">$$precio</h3>
                                        <p class="text-center m-0">Impuestos y cargos incluidos</p>
                                        $txtAlertNoHab
                                        <p class="text-center mx-5 my-2 mb-0 p-1 dato-red1" style="border: 2px solid red; margin: 6px 33%;">100% Reembolsable</p>
                                        <div class="row w-100 m-0 mb-2">
                                            <div class="m-0 p-0 d-flex justify-content-center mt-1">
                                                $txtPoliticasCancelacion
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <p class="mb-3">$description</p>
                                        <div class="row w-100 m-0 p-0 mb-3">
                                            
                                            <div class="m-0 p-0 d-flex justify-content-center">
                                            <a class="btn rounded-0 text-white p-1 btnDetallesHotel" href="./../detalleshotel?code=$codigoHotel" style="background: #e3223e; font-size: 14px; width: 160px;">Ver Habitaciones</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div id="destino-img" class="col-md-4" style="background-size:cover; background-image:url($img);">
                            
                        </div>
                    </div>
                    ';
                
                    for ($a=0; $a < $hotelEstrellas; $a++) { 
                        $htmlEstrellas .= '<img class="star-hotel mt-1" style="height: 17px;" src="medios/img/Estrellarecomendacionesgrande.png" alt="">';
                    }
                
                    $precioMXN = $GetHoteles["minRate"][$i] * $valor[$divisa];
                    $precioMXN = number_format($precioMXN, 2);
                
                        $vars = array(
                            '$nombreHotel'                      => $GetHoteles["nombreHotel"][$i],
                            '$destinationName'                  => $GetHoteles["destinationName"][$i],
                            '$description'                      => $descripcion,
                            '$ubicacionMapa'                    => "https://www.google.com/maps/embed/v1/search?key=AIzaSyCS7kK67VZxjgmzINsI1_C4zamwkNaUaD4&q= " . str_replace("&", "and", $GetHoteles['nombreHotel'][$i] . "+" .$GetHoteles['destinationName'][$i]) . "&center={$GetHoteles['latitude'][$i]},{$GetHoteles['longitude'][$i]}&zoom=18",
                            '$distancia'                        => $txtDistancia,
                            '$destino'                          => $txtDestino,
                            '$estrellas'                        => $htmlEstrellas,
                            '$noHabitaciones'                   => $noHabitaciones,
                            '$precio'                           => $precioMXN,
                            '$img'                              => $img,
                            '$pagina'                           => $pagina,
                            '$codigoHotel'                      => $GetHoteles['code'][$i],
                            '$txtAdultosMenoresHabitaciones'    => $txtAdultosMenoresHabitaciones,
                            '$nochesEstancia'                   => ($nochesEstancia->days == 1) ? '1 Noche' : $nochesEstancia->days . ' Noches',
                            '$txtFacilidades'                   => $txtFacilidades,
                            '$txtPoliticasCancelacion'          => $txtPoliticasCancelacion,
                            '$popoverTiposHabitacion'           => $popoverTiposHabitacion,
                            '$txtAlertNoHab'                    => $txtAlertNoHab,
                        );
                
                    echo strtr($template, $vars);
                }
            ?>

            <div>
                <nav>
                    <div class="row w-100">
                        <div class="col-xs-12 col-sm-6">
                            <h4 class="pag-num-hot fw-bold">Mostrando <?php echo ($GetContadorHoteles['contador'][0] < $HotelPorPagina) ? $GetContadorHoteles['contador'][0] : $HotelPorPagina; ?> de <?php echo $GetContadorHoteles['contador'][0]; ?> Hoteles disponibles</h4>
                        </div>
                        <div class="col-xs-12 col-sm-6">
                            <p class="pag-num-pag"><b>Página</b> <?php echo $pagina ?> de <?php echo $paginas ?> </p>
                        </div>
                    </div>
                    <ul class="pagination">
                        <!-- Si la página actual es mayor a uno, mostramos el botón para ir una página atrás -->
                        <?php if ($pagina > 1) { ?>
                            <li class="paginacion">
                                <a href="./../motordebusqueda?pagina=<?php echo $pagina - 1 ?>">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                        <?php } ?>

                        <!-- Mostramos enlaces para ir a todas las páginas. Es un simple ciclo for-->
                        <?php for ($x = 1; $x <= $paginas; $x++) { ?>
                            <li class="<?php if ($x == $pagina) echo "active" ?> paginacion">
                                <a class="pag-act fw-bold" href="./../motordebusqueda?pagina=<?php echo $x ?>">
                                    <?php echo $x ?></a>
                            </li>
                        <?php } ?>
                        <!-- Si la página actual es menor al total de páginas, mostramos un botón para ir una página adelante -->
                        <?php if ($pagina < $paginas) { ?>
                            <li class="paginacion">
                                <a href="./../motordebusqueda?pagina=<?php echo $pagina + 1 ?>">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        <?php } ?>
                    </ul>
                </nav>
            </div>
            <?php } else { ?>
                <div class="container mt-5 mb-3 d-flex justify-content-center flex-column align-items-center">
                    <div class="d-flex justify-content-center gap-3">
                        <img src="./medios/img/iconset/code.png" alt="Code" title="Icono Programación">
                    </div>

                    <div class="mt-4 w-75 text-center mb-4">
                        <h2 class="fw-bold text-uppercase">No hemos encontrado hoteles para esta busqueda!</h2>

                        <p class="text-center mt-4" style="font-size: 1.2rem !important;">
                            Es probable que esto se deba a un problema con el servidor o con el proveedor de servicios, vuelva a intentar en unos momentos.
                        </p>
                    </div>

                    <div class="d-flex justify-content-center gap-3 mb-5 flex-wrap">
                        <a class="btn btn-primary fw-bold"  href="./../">Ir a la pagina principal</a>
                        <a class="btn btn-secondary fw-bold" href="./../destinos">Ver Destinos</a>
                    </div>

                    <div class="d-flex justify-content-center gap-3 flex-wrap">
                        <img style="width: 7rem;" src="./medios/img/iconset/Ticket.png" alt="Ticket" title="Icono Ticket">
                        <img style="width: 7rem;" src="./medios/img/iconset/Earth.png" alt="Earth" title="Icono Mundo">
                        <img style="width: 7rem;" src="./medios/img/iconset/Hotel4.png" alt="Hotel" title="Icono Hotel">
                        <img style="width: 7rem;" src="./medios/img/iconset/Plane2.png" alt="Plane" title="Icono Avion">
                    </div>

                </div>
            <?php } ?>
        </div> 
    </div>
    <!--FIN PRINCIPAL SIDEBAR-->

    <!--FIN BODY-->

    <!--FOOTER-->
    <?php include ("footer.php") ?>
    <!--FIN FOOTER-->

    <script src="js/select2/select2.min.js"></script>
    <script type="text/javascript" src="js/filtro.js"></script>
    <script type="text/javascript" src="js/motordebusqueda.js"></script>
</body>
</html>

<!-- Rango de precios -->
<?php if (isset($response["hotels"]["hotels"])) { ?>
<script>
    $(document).ready(function() {
        let comprobarLimiteInferior = function(valorInferior, valorSuperior) {
            if (valorInferior >= valorSuperior) {
                valorInferior = valorSuperior - 1;
            } else if (valorInferior <= <?php echo floor(min($minRates) * $valor[$divisaMasRepetida]) ?>) {
                valorInferior = <?php echo floor(min($minRates) * $valor[$divisaMasRepetida]) ?> ;
            }

            return valorInferior;
        }

        let comprobarLimiteSuperior = function(valorInferior, valorSuperior) {
            if (valorSuperior <= valorInferior) {
                valorSuperior = valorInferior + 1;
            } else if (valorSuperior >= <?php echo ceil(max($minRates) * $valor[$divisaMasRepetida] + 400) ?>) {
                valorSuperior = <?php echo ceil(max($minRates) * $valor[$divisaMasRepetida] + 400) ?> ;
            }

            return valorSuperior;
        }

        let actualizarValoresSlider = function() {
            $("#min_price").val( comprobarLimiteInferior(Number($("#min_price").val()), Number($("#max_price").val())) );
            $("#max_price").val( comprobarLimiteSuperior(Number($("#min_price").val()), Number($("#max_price").val())) );

            $("#slider-range").slider({
                values: [$("#min_price").val(), $("#max_price").val()]
            });
        }

        let actualizarValoresSliderMovil = function() {
            $("#min_price-movil").val( comprobarLimiteInferior(Number($("#min_price-movil").val()), Number($("#max_price-movil").val())) );
            $("#max_price-movil").val( comprobarLimiteSuperior(Number($("#min_price-movil").val()), Number($("#max_price-movil").val())) );

            $("#slider-range-movil").slider({
                values: [$("#min_price-movil").val(), $("#max_price-movil").val()]
            });
        }


        $("#min_price, #max_price").on('change', function(event) {
            actualizarValoresSlider();
        });

        $("#min_price-movil, #max_price-movil").on('change', function(event) {
            actualizarValoresSliderMovil();
        });

        // En esta funcion se maneja como se comportara el slider cuando se presionan las teclas de direccion arriba(38) y abajo(40)
        $("#min_price, #max_price").on("keydown", function(event) {

            if (event.target.id === 'min_price') {
                if (event.keyCode == 38) {
                    $("#min_price").val(    Number($("#min_price").val()) + 10   );
                } else if (event.keyCode == 40) {
                    $("#min_price").val(    Number($("#min_price").val()) - 10   );
                }
            } else {
                if (event.keyCode == 38) {
                    $("#max_price").val(    Number($("#max_price").val()) + 10   );
                } else if (event.keyCode == 40) {
                    $("#max_price").val(    Number($("#max_price").val()) - 10   );
                }
            }

            if ( (event.keyCode == 38) || (event.keyCode == 40) ) {
                actualizarValoresSlider();
            }
        });
        
        $("#min_price, #max_price").on("paste", function(event) {
            actualizarValoresSlider();
        });

        $("#min_price-movil, #max_price-movil").on("paste", function(event) {
            actualizarValoresSlider();
        });

        // Inicializacion del Slider de PC
        $("#slider-range").slider({
            range: true,
            orientation: "horizontal",
            min:        <?php echo floor(   min($minRates) * $valor[$divisaMasRepetida]) ?>,
            
            // La suma de 400 es para evitar que el precio maximo nunca salga en los filtros a causa de perdida de decimales en el calculo o cambio en el valor de la moneda
            max:        <?php echo ceil(    max($minRates) * $valor[$divisaMasRepetida] + 400) ?>,
            values: [   <?php echo floor(   min($minRates) * $valor[$divisaMasRepetida]) ?>, <?php echo ceil(max($minRates) * $valor[$divisaMasRepetida] + 400) ?>],
            
            step: 50,

            slide: function(event, ui) {
                if (ui.values[0] == ui.values[1]) {
                    return false;
                }

                $("#min_price").val(    ui.values[0]    );
                $("#max_price").val(    ui.values[1]    );
            }
        });

        // Inicializacion del Slider version movil
        $("#slider-range-movil").slider({
            range: true,
            orientation: "horizontal",
            min:        <?php echo floor(   min($minRates) * $valor[$divisaMasRepetida]) ?>,
            
            // La suma de 400 es para evitar que el precio maximo nunca salga en los filtros a causa de perdida de decimales en el calculo o cambio en el valor de la moneda
            max:        <?php echo ceil(    max($minRates) * $valor[$divisaMasRepetida] + 400) ?>,
            values: [   <?php echo floor(   min($minRates) * $valor[$divisaMasRepetida]) ?>, <?php echo ceil(max($minRates) * $valor[$divisaMasRepetida] + 400) ?>],
            
            step: 50,

            slide: function(event, ui) {
                if (ui.values[0] == ui.values[1]) {
                    return false;
                }

                $("#min_price-movil").val(    ui.values[0]    );
                $("#max_price-movil").val(    ui.values[1]    );
            }
        });

        // Se inicializan los textos de el filtro de precio a los valores establecidos en los extremos del slicer
        // PC
        $("#min_price").val(    $("#slider-range").slider("values", 0)  );
        $("#max_price").val(    $("#slider-range").slider("values", 1)  );

        // Movil
        $("#min_price-movil").val(    $("#slider-range-movil").slider("values", 0)  );
        $("#max_price-movil").val(    $("#slider-range-movil").slider("values", 1)  );
    });
</script>
<?php } else { ?>
<script>
$(document).ready(function() {

    // Inicializacion del Slider de PC
    $("#slider-range").slider({
        range: true,
        orientation: "horizontal",
        min:        0,
        
        // La suma de 400 es para evitar que el precio maximo nunca salga en los filtros a causa de perdida de decimales en el calculo o cambio en el valor de la moneda
        max:        1000,
        values: [   0, 1000],
        
        step: 50,

        slide: function(event, ui) {
            if (ui.values[0] == ui.values[1]) {
                return false;
            }

            $("#min_price").val(    ui.values[0]    );
            $("#max_price").val(    ui.values[1]    );
        }
    });

    // Inicializacion del Slider version movil
    $("#slider-range-movil").slider({
        range: true,
        orientation: "horizontal",
        min:        0,
        
        // La suma de 400 es para evitar que el precio maximo nunca salga en los filtros a causa de perdida de decimales en el calculo o cambio en el valor de la moneda
        max:        1000,
        values: [   0, 1000],
        
        step: 50,

        slide: function(event, ui) {
            if (ui.values[0] == ui.values[1]) {
                return false;
            }

            $("#min_price-movil").val(    ui.values[0]    );
            $("#max_price-movil").val(    ui.values[1]    );
        }
    });

    // Se inicializan los textos de el filtro de precio a los valores establecidos en los extremos del slicer
    // PC
    $("#min_price").val(    $("#slider-range").slider("values", 0)  );
    $("#max_price").val(    $("#slider-range").slider("values", 1)  );

    // Movil
    $("#min_price-movil").val(    $("#slider-range-movil").slider("values", 0)  );
    $("#max_price-movil").val(    $("#slider-range-movil").slider("values", 1)  );
});
</script>
<?php } ?>

<script>
    function filtroEstrellas($dispositivo) {
        let data;

        if( $dispositivo != 'movil' ) {
            data = $("#filtrosForm").serialize();
        } else {
            data = $("#filtrosFormMovil").serialize();
        }

        $.ajax({
            data:  data,
            url:   'filtrados_de_busqueda.php',
            type:  'post',
            beforeSend: function () {
                    $("#hotelesList").html("");
                    let timerInterval
                    Swal.fire({
                    title: '¡Filtrando la busqueda!',
                    html: 'Este mensaje se cerrara automaticamente',
                    timer: 7000,
                    timerProgressBar: true,
                    didOpen: () => {
                        Swal.showLoading()
                    }
                }).then((result) => {
                    /* Read more about handling dismissals below */
                    if (result.dismiss === Swal.DismissReason.timer) {
                        // console.log('I was closed by the timer');
                    }
                });
            },
            success:  function (response) {
                // Agrega el html de la respuesta a la pagina ya renderizada
                $("#hotelesList").html(response);

                // Vuelve a iniciar los mapas embebidos
                $(document).ready(function(){
                    $('.venoboxframe').venobox(); 
                });

                // Vuelve a activar los pop overs
                var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
                var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
                    return new bootstrap.Popover(popoverTriggerEl)
                });

                // Vuelve añadir los eventos de sweet alert a los botones de detalles de habitacion
                for (const botonDetalle of document.getElementsByClassName("btnDetallesHotel") ) {
                    botonDetalle.addEventListener("click", function() {
                        let timerInterval
                        Swal.fire({
                        title: 'Obteniendo Información',
                        html: `Esto puede tardar unos segundos...`,
                            didOpen: () => {
                                Swal.showLoading()
                            },
                        })
                    })
                }
            }
        }); 
    }

    function PaginacionAjax(res,filtroestrella,filtrocama,filtroplanes,premin,premax,filtropagina,codigotabla){
        if(res=1){
            var estrellas  = filtroestrella;
            var camas = filtrocama;
            var planes = filtroplanes;
            var pagina = filtropagina;
            var codigotabla = codigotabla;
            // console.log("categoria="+estrellas+"&tipCama="+camas+"&tipPlanes="+planes+"&pagina="+pagina+"&codigotabla="+codigotabla);
            $.ajax({
                    data:  "categoria="+estrellas+"&tipCama="+camas+"&tipPlanes="+planes+"&pagina="+pagina+"&codigotabla="+codigotabla+"&precioMin="+premin+"&precioMax="+premax,
                    url:   'filtrados_de_busqueda.php',
                    type:  'post',
                    beforeSend: function () {
                        $("#hotelesList").html("");
                        let timerInterval
                        Swal.fire({
                        title: '¡Filtrando la busqueda!',
                        html: 'Este mensaje se cerrara automaticamente',
                        timer: 7000,
                        timerProgressBar: true,
                        didOpen: () => {
                            Swal.showLoading()
                            const b = Swal.getHtmlContainer().querySelector('b')
                            timerInterval = setInterval(() => {
                            b.textContent = Swal.getTimerLeft()
                            }, 100)
                        },
                        willClose: () => {
                            clearInterval(timerInterval)
                        }
                        }).then((result) => {
                        /* Read more about handling dismissals below */
                        if (result.dismiss === Swal.DismissReason.timer) {
                            console.log('I was closed by the timer')
                        }
                        });
                    },
                    success:  function (response) {
                        console.log(response);
                        $("#hotelesList").html(response);
                    }
            });
        }
    }
</script>