<?php
header("Content-Type: application/json; charset = UTF-8");
include("../clases/Types.class.php");

use TypesHotelBeds\TypesHotel;

$type = new TypesHotel();

 // // Your API Key and secret from developer.hotelbeds.com
 $apiKey = "3a776822728123a27b049472357e058d";  
 $Secret = "0784f933dc";

// // Signature is generated by SHA256 (Api-Key + Secret + Timestamp (in seconds))
 $signature = hash("sha256", $apiKey.$Secret.time());
 //Facilities

for($i=1;$i<4;$i++){
 switch($i){
     case 1:
        $inicial = 1;
    break;
     case 2:
        $inicial = 1001;
    break;
     case 3:
        $inicial = 2001;
    break;
 }
 $curl = curl_init();
 curl_setopt_array($curl, array(
     CURLOPT_URL => "https://api.test.hotelbeds.com/hotel-content-api/1.0/types/facilities?fields=all&language=CAS&from=$inicial&to=".$i."000&useSecondaryLanguage=True",
     CURLOPT_RETURNTRANSFER => true,
     CURLOPT_ENCODING => "",
     CURLOPT_MAXREDIRS => 10,
     CURLOPT_TIMEOUT => 30,
     CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
     CURLOPT_CUSTOMREQUEST => "GET",
     CURLOPT_HTTPHEADER => array(
         "accept: application/json",
         "accept-encoding: gzip",
         "api-key: ". $apiKey ."",
         "cache-control: no-cache",
         "content-type: application/json",
         "x-signature: ". $signature .""
     ),
 ));

 $responseFacilities = curl_exec($curl);
 $err = curl_error($curl);
 curl_close($curl);

 
 $respuestaFacilities = $type->Facilities($responseFacilities);

 //Guardado de FacilitiesGruop

 $curl = curl_init();
 curl_setopt_array($curl, array(
     CURLOPT_URL => "https://api.test.hotelbeds.com/hotel-content-api/1.0/types/facilitygroups?fields=all&language=CAS&from=$inicial&to=".$i."000&useSecondaryLanguage=True",
     CURLOPT_RETURNTRANSFER => true,
     CURLOPT_ENCODING => "",
     CURLOPT_MAXREDIRS => 10,
     CURLOPT_TIMEOUT => 30,
     CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
     CURLOPT_CUSTOMREQUEST => "GET",
     CURLOPT_HTTPHEADER => array(
         "accept: application/json",
         "accept-encoding: gzip",
         "api-key: ". $apiKey ."",
         "cache-control: no-cache",
         "content-type: application/json",
         "x-signature: ". $signature .""
     ),
 ));

 $responseFacilitiesGroup = curl_exec($curl);
 $err = curl_error($curl);
 curl_close($curl);
 $respuestaFacilitiesGroup = $type->FacilitiesGruop($responseFacilitiesGroup);

  //Guardado de FacilitiesTypologies

 $curl = curl_init();
 curl_setopt_array($curl, array(
     CURLOPT_URL => "https://api.test.hotelbeds.com/hotel-content-api/1.0/types/facilitytypologies?fields=all&language=CAS&from=$inicial&to=".$i."000&useSecondaryLanguage=True",
     CURLOPT_RETURNTRANSFER => true,
     CURLOPT_ENCODING => "",
     CURLOPT_MAXREDIRS => 10,
     CURLOPT_TIMEOUT => 30,
     CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
     CURLOPT_CUSTOMREQUEST => "GET",
     CURLOPT_HTTPHEADER => array(
         "accept: application/json",
         "accept-encoding: gzip",
         "api-key: ". $apiKey ."",
         "cache-control: no-cache",
         "content-type: application/json",
         "x-signature: ". $signature .""
     ),
 ));

 $responseFacilitiesTypologies = curl_exec($curl);
 $err = curl_error($curl);
 curl_close($curl);
 $respuestaFacilitiesTypologies = $type->FacilitiesTypologies($responseFacilitiesTypologies);

 //Guardado de Rooms

 $curl = curl_init();
 curl_setopt_array($curl, array(
     CURLOPT_URL => "https://api.test.hotelbeds.com/hotel-content-api/1.0/types/rooms?fields=all&language=CAS&from=$inicial&to=".$i."000&useSecondaryLanguage=True",
     CURLOPT_RETURNTRANSFER => true,
     CURLOPT_ENCODING => "",
     CURLOPT_MAXREDIRS => 10,
     CURLOPT_TIMEOUT => 30,
     CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
     CURLOPT_CUSTOMREQUEST => "GET",
     CURLOPT_HTTPHEADER => array(
         "accept: application/json",
         "accept-encoding: gzip",
         "api-key: ". $apiKey ."",
         "cache-control: no-cache",
         "content-type: application/json",
         "x-signature: ". $signature .""
     ),
 ));

 $responseRooms = curl_exec($curl);
 $err = curl_error($curl);
 curl_close($curl);
 $respuestaRooms = $type->Rooms($responseRooms);

 //Guardado de Promotions

 $curl = curl_init();
 curl_setopt_array($curl, array(
     CURLOPT_URL => "https://api.test.hotelbeds.com/hotel-content-api/1.0/types/promotions?fields=all&language=CAS&from=$inicial&to=".$i."000&useSecondaryLanguage=True",
     CURLOPT_RETURNTRANSFER => true,
     CURLOPT_ENCODING => "",
     CURLOPT_MAXREDIRS => 10,
     CURLOPT_TIMEOUT => 30,
     CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
     CURLOPT_CUSTOMREQUEST => "GET",
     CURLOPT_HTTPHEADER => array(
         "accept: application/json",
         "accept-encoding: gzip",
         "api-key: ". $apiKey ."",
         "cache-control: no-cache",
         "content-type: application/json",
         "x-signature: ". $signature .""
     ),
 ));

 $responsePromotions = curl_exec($curl);
 $err = curl_error($curl);
 curl_close($curl);
 $respuestaPromotions = $type->Promotions($responsePromotions);

 //Guardado de Categories

 $curl = curl_init();
 curl_setopt_array($curl, array(
     CURLOPT_URL => "https://api.test.hotelbeds.com/hotel-content-api/1.0/types/categories?fields=all&language=CAS&from=$inicial&to=".$i."000&useSecondaryLanguage=True",
     CURLOPT_RETURNTRANSFER => true,
     CURLOPT_ENCODING => "",
     CURLOPT_MAXREDIRS => 10,
     CURLOPT_TIMEOUT => 30,
     CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
     CURLOPT_CUSTOMREQUEST => "GET",
     CURLOPT_HTTPHEADER => array(
         "accept: application/json",
         "accept-encoding: gzip",
         "api-key: ". $apiKey ."",
         "cache-control: no-cache",
         "content-type: application/json",
         "x-signature: ". $signature .""
     ),
 ));

 $responseCategories = curl_exec($curl);
 $err = curl_error($curl);
 curl_close($curl);
 $respuestaCategories = $type->Categories($responseCategories);

 //Guardado de Group Categories

 $curl = curl_init();
 curl_setopt_array($curl, array(
     CURLOPT_URL => "https://api.test.hotelbeds.com/hotel-content-api/1.0/types/groupcategories?fields=all&language=CAS&from=$inicial&to=".$i."000&useSecondaryLanguage=True",
     CURLOPT_RETURNTRANSFER => true,
     CURLOPT_ENCODING => "",
     CURLOPT_MAXREDIRS => 10,
     CURLOPT_TIMEOUT => 30,
     CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
     CURLOPT_CUSTOMREQUEST => "GET",
     CURLOPT_HTTPHEADER => array(
         "accept: application/json",
         "accept-encoding: gzip",
         "api-key: ". $apiKey ."",
         "cache-control: no-cache",
         "content-type: application/json",
         "x-signature: ". $signature .""
     ),
 ));

 $responseCategoriesGroup = curl_exec($curl);
 $err = curl_error($curl);
 curl_close($curl);
 $respuestaCategoriesGroup = $type->CategoriesGroup($responseCategoriesGroup);


 //Guardado de Destinations

$curl = curl_init();
curl_setopt_array($curl, array(
    CURLOPT_URL => "https://api.test.hotelbeds.com/hotel-content-api/1.0/locations/destinations?fields=all&language=CAS&from=$inicial&to=".$i."000&useSecondaryLanguage=false",
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => "",
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 30,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => "GET",
    CURLOPT_HTTPHEADER => array(
        "accept: application/json",
        "accept-encoding: gzip",
        "api-key: ". $apiKey ."",
        "cache-control: no-cache",
        "content-type: application/json",
        "x-signature: ". $signature .""
    ),
));

$responseDestinations = curl_exec($curl);
$err = curl_error($curl);
curl_close($curl);
$respuestaDestinations = $type->Destinations($responseDestinations);

}

 //Guardado de Countries

 $curl = curl_init();
 curl_setopt_array($curl, array(
     CURLOPT_URL => "https://api.test.hotelbeds.com/hotel-content-api/1.0/locations/countries?fields=all&language=CAS&from=1&to=1000",
     CURLOPT_RETURNTRANSFER => true,
     CURLOPT_ENCODING => "",
     CURLOPT_MAXREDIRS => 10,
     CURLOPT_TIMEOUT => 30,
     CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
     CURLOPT_CUSTOMREQUEST => "GET",
     CURLOPT_HTTPHEADER => array(
         "accept: application/json",
         "accept-encoding: gzip",
         "api-key: ". $apiKey ."",
         "cache-control: no-cache",
         "content-type: application/json",
         "x-signature: ". $signature .""
     ),
 ));

 $responseCountries = curl_exec($curl);
 $err = curl_error($curl);
 curl_close($curl);
 $respuestaCountries = $type->Countries($responseCountries);

echo $respuestaCountries;
 
 ?>